### ISSUE TITLE
Dread-steed for the win

### ISSUE THREAD

**Issue by skbolton** [sandman45/dread-steed#9]
Hey I am one of the new Developers on Gemini at Vivint Solar and I am writing a SalesForce ORM (wish me luck) and I am going to wrap Dread-steed and use it as the pool manager. I was wondering if we could add a config to pass into Dread-steed to silence the console.logs that it does. That way when writing the tests for my module my output isn't clogged with the pool messages. 
I am willing to do the work and submit the pr if you think this is a good idea. Let me know

**Comment by sandman45** [comment]
Stephen,

Sounds good to me man! just submit a PR and I'll get it approved.

Oh and Good Luck 🤞 🍀 ;)

-Matt
